# Generated by Django 2.0.6 on 2018-06-05 10:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instruction', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Choice1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Choice2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Choice3', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Choice4', ckeditor_uploader.fields.RichTextUploadingField()),
                ('right_choice', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Father_name', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='questions_answer',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student_details'),
        ),
        migrations.AddField(
            model_name='questions_answer',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questions'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='Tname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test'),
        ),
        migrations.AddField(
            model_name='category',
            name='Tname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test'),
        ),
    ]
