# Generated by Django 2.2.2 on 2019-06-29 06:52

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20190123_0507'), ('core', '0003_auto_20190123_0524'), ('core', '0004_auto_20190123_0817'), ('core', '0005_auto_20190123_0818'), ('core', '0006_auto_20190123_1141'), ('core', '0007_auto_20190123_1142'), ('core', '0008_auto_20190123_1144'), ('core', '0009_remove_marks_percentage'), ('core', '0010_auto_20190625_0851'), ('core', '0011_auto_20190628_0812')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std_no', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='400', message='Invalid Student Number', regex='^\\d{7}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('father', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[6789]\\d{9}$')])),
                ('branch', models.CharField(blank=True, max_length=5, null=True)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('designer', models.CharField(blank=True, max_length=255, null=True)),
                ('hosteler', models.CharField(blank=True, max_length=3, null=True)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=4)),
                ('university_roll_no', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='invalid university roll no.', regex='^[1]\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225)),
                ('total_question_display', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('choice1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('choice2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('choice3', ckeditor_uploader.fields.RichTextUploadingField()),
                ('choice4', ckeditor_uploader.fields.RichTextUploadingField()),
                ('correct_choice', models.PositiveIntegerField()),
                ('negative', models.BooleanField(default=False)),
                ('negative_marks', models.IntegerField(blank=True, null=True)),
                ('marks', models.IntegerField(default=1, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.IntegerField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(default=1)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
                ('question_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('on_or_off', models.BooleanField()),
                ('negative', models.BooleanField(default=False)),
                ('std_no', models.BooleanField(default=False)),
                ('father_name', models.BooleanField(default=False)),
                ('phone_number', models.BooleanField(default=False)),
                ('branch', models.BooleanField(default=False)),
                ('skills', models.BooleanField(default=False)),
                ('designer', models.BooleanField(default=False)),
                ('hosteler', models.BooleanField(default=False)),
                ('year', models.BooleanField(default=False)),
                ('university_roll_no', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test'),
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('on_or_off', models.BooleanField()),
                ('additional_question', models.ManyToManyField(to='core.AdditionalQuestion')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', ckeditor_uploader.fields.RichTextUploadingField()),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Test')),
            ],
            options={
                'verbose_name_plural': 'Instructions',
            },
        ),
    ]
