# Generated by Django 2.0.6 on 2018-06-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedanswer',
            name='selected_choice',
            field=models.IntegerField(blank=True),
        ),
    ]
