# Generated by Django 2.0.6 on 2018-06-10 13:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
