# Generated by Django 2.0.6 on 2018-06-16 06:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='test_name',
            field=models.CharField(max_length=100, null=core.models.Test),
        ),
    ]
