# Generated by Django 2.0.6 on 2018-07-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='father_name',
        ),
    ]
