# Generated by Django 2.0.6 on 2018-06-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'verbose_name_plural': 'Instructions'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(),
        ),
    ]
