# Generated by Django 2.0.6 on 2018-07-25 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='branch',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='designer',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hosteler',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='std_no',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7}$')]),
        ),
    ]
