# Generated by Django 2.0.6 on 2018-06-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number_of_questions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
