# Generated by Django 2.0.6 on 2018-06-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
        migrations.AddField(
            model_name='category',
            name='total_question_display',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
