# Generated by Django 2.0.6 on 2019-01-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=4),
        ),
        migrations.AddField(
            model_name='test',
            name='year',
            field=models.BooleanField(default=False),
        ),
    ]
