# Generated by Django 2.0.6 on 2018-10-22 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='branch',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='designer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='father',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hosteler',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='std_no',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='test_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
