# Generated by Django 2.2.2 on 2019-07-30 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0011_auto_20190628_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[56789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='university_roll_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.IntegerField(default=-1),
        ),
    ]
