# Generated by Django 2.0.6 on 2018-06-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_number_of_questions'),
        ('core', '0002_auto_20180622_0941'),
    ]

    operations = [
    ]
