# Generated by Django 2.0.6 on 2018-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180728_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='negative',
            field=models.BooleanField(default=False),
        ),
    ]
