# Generated by Django 2.0.6 on 2018-06-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180611_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedanswer',
            name='status',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
