# Generated by Django 2.0.6 on 2018-07-23 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='branch',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='designer',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hosteler',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='student_no',
            field=models.CharField(max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[789]\\d{9}$')]),
        ),
    ]
