# Generated by Django 2.0.6 on 2018-06-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='on_or_off',
        ),
    ]
