# Generated by Django 2.2.2 on 2019-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190730_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='university_roll_no',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
