# Generated by Django 2.0.6 on 2018-06-10 13:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180610_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
