# Generated by Django 2.0.6 on 2018-07-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180725_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='designer',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='marks',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate'),
        ),
    ]
