# Generated by Django 2.0.6 on 2018-06-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=5000)),
                ('negative', models.BooleanField()),
                ('negative_marks', models.IntegerField(null=True)),
                ('marks', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=2000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
            ],
        ),
        migrations.AddField(
            model_name='correctchoice',
            name='correct_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.QuestionChoice'),
        ),
        migrations.AddField(
            model_name='correctchoice',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
    ]
