# Generated by Django 2.0.6 on 2018-06-10 13:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180610_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
