# Generated by Django 2.0.6 on 2018-06-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_test_on_or_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='on_or_off',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
