# Generated by Django 2.0.6 on 2018-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180607_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
