# Generated by Django 2.0.6 on 2018-07-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_test_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='test_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Test'),
            preserve_default=False,
        ),
    ]
