# Generated by Django 2.0.6 on 2018-06-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
