# Generated by Django 2.0.6 on 2018-07-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20180622_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number_of_questions',
        ),
    ]
