# Generated by Django 2.0.6 on 2018-07-24 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180723_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='hosteler',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='student_no',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^[789]\\d{9}$')]),
        ),
    ]
