# Generated by Django 2.0.6 on 2018-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_test_on_or_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.TimeField(),
        ),
    ]
