# Generated by Django 2.0.6 on 2019-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190802_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
