# Generated by Django 2.0.6 on 2018-06-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
