# Generated by Django 2.0.6 on 2018-06-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180605_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctchoice',
            name='correct_choice',
        ),
        migrations.RemoveField(
            model_name='correctchoice',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CorrectChoice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
    ]
