# Generated by Django 2.0.6 on 2018-07-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_candidate_father_name'),
        ('core', '0004_marks_test_name'),
    ]

    operations = [
    ]
