# Generated by Django 2.0.6 on 2018-06-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180614_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
