# Generated by Django 2.0.6 on 2018-06-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180607_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Candidate',
        ),
    ]
