# Generated by Django 2.2.2 on 2019-08-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190805_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test')),
            ],
            options={
                'unique_together': {('candidate', 'category')},
            },
        ),
    ]
