# Generated by Django 2.0.6 on 2018-07-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20180728_1441'),
        ('core', '0005_merge_20180728_1327'),
    ]

    operations = [
    ]
