# Generated by Django 2.0.6 on 2018-06-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
