# Generated by Django 2.0.6 on 2019-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190805_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.IntegerField(default=0),
        ),
    ]
