# Generated by Django 2.0.6 on 2018-07-29 12:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20180728_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test')),
            ],
        ),
    ]
