# Generated by Django 2.0.6 on 2018-09-06 11:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_designquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('on_or_off', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AddField(
            model_name='additional',
            name='additional_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdditionalQuestion'),
        ),
        migrations.AddField(
            model_name='additional',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test'),
        ),
    ]
