# Generated by Django 2.0.6 on 2019-08-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190816_1037'),
        ('core', '0006_auto_20190810_0706'),
    ]

    operations = [
    ]
