# Generated by Django 2.0.6 on 2019-08-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20190817_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.IntegerField(default=1),
        ),
    ]
