# Generated by Django 2.0.6 on 2018-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180906_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='additional_question',
        ),
        migrations.AddField(
            model_name='additional',
            name='additional_question',
            field=models.ManyToManyField(to='core.AdditionalQuestion'),
        ),
    ]
