# Generated by Django 2.0.6 on 2019-01-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190123_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='percentage',
        ),
    ]
