# Generated by Django 2.0.6 on 2018-09-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180906_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='test',
        ),
        migrations.RemoveField(
            model_name='designquestion',
            name='test',
        ),
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.DeleteModel(
            name='DesignQuestion',
        ),
    ]
