# Generated by Django 2.0.6 on 2018-06-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180607_1515'),
        ('core', '0007_instruction'),
    ]

    operations = [
    ]
