# Generated by Django 2.2.2 on 2019-06-25 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_marks_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[6789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='std_no',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='400', message='Invalid Student Number', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='university_roll_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='invalid university roll no.', regex='^[1]\\d{9}$')]),
        ),
    ]
