# Generated by Django 2.0.6 on 2019-08-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190817_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorymarks',
            unique_together={('candidate', 'category')},
        ),
    ]
