# Generated by Django 2.2.2 on 2019-06-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190625_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Test'),
        ),
    ]
