# Generated by Django 2.0.6 on 2019-08-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190817_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('unanswered', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='catmarks',
            unique_together={('candidate', 'category')},
        ),
    ]
