# Generated by Django 2.0.6 on 2019-08-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190817_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catmarks',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='catmarks',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='catmarks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='catmarks',
            name='test',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='test_name',
            new_name='test',
        ),
        migrations.AddField(
            model_name='marks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AddField(
            model_name='marks',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='unanswered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('candidate', 'category')},
        ),
        migrations.DeleteModel(
            name='CatMarks',
        ),
    ]
